name: Check HTML File Upload

on:
  push:
    paths:
      - 'Vocabulary.xlsx'  # Trigger the workflow when Vocabulary.xlsx is pushed to the repo

jobs:
  check_html_file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install gitpython

      # Step 4: Check if HTML file was uploaded after the Excel file
      - name: Check if HTML file was uploaded after Excel
        run: |
          python check_html_uploaded.py

      # Step 5: Prompt to upload HTML file if it was not uploaded after Excel
      - name: Prompt for HTML file upload
        if: failure()  # Only run this step if the previous step failed (HTML file is missing or uploaded before Excel)
        run: |
          echo "Please upload the HTML file after running the batch script to convert the Excel file to HTML."
          echo "Once uploaded, the workflow will continue automatically."

      # Step 6: Wait for the HTML file to be uploaded and then proceed to commit and push
      - name: Wait for HTML file upload
        if: failure()  # This step will be skipped until the HTML file is uploaded
        run: |
          echo "Waiting for the HTML file to be uploaded..."
          exit 1  # Make the workflow pause here so you can upload the HTML file manually

      # Step 7: Commit and Push the generated HTML file (if HTML file is uploaded after Excel)
      - name: Commit and Push HTML file
        if: success()  # Only run this step if the check passed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add grammatik_table.html  # Ensure this is the file you want to commit
          git commit -m "Add updated HTML file from Excel conversion" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
